#!/usr/bin/env bash

_git_as() {
    local cur git_command profiles profile_found

    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()
    profiles=$(find "$GIT_PROFILE_DIR" -type f -name '.*' -exec basename {} \; 2>/dev/null | sed 's/^\.//')

    # Check if any profile is already in the command
    profile_found=false
    for profile in $profiles; do
        for word in "${COMP_WORDS[@]}"; do
            if [[ "$word" == "$profile" ]]; then
                profile_found=true
                break 2
            fi
        done
    done

    if [[ "$profile_found" == false ]]; then
        COMPREPLY=( $(compgen -W "$profiles -h" -- "$cur") )
    elif [[ ${#COMP_WORDS[@]} -eq 3 ]]; then
        COMPREPLY=( $(compgen -W "add commit push pull status checkout branch cherry-pick stash fetch rm clone" -- "$cur") )
    else
        git_command="${COMP_WORDS[2]}"
        if command -v __git_complete >/dev/null 2>&1; then
            __git_complete "$cur" "$git_command"
        fi
    fi

    return 0
}
