#!/usr/bin/env bash

_git_as() {
    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    local profiles
    profiles=$(find "$GIT_PROFILE_DIR" -type f -name '.*' -exec basename {} \; 2>/dev/null | sed 's/^\.//')

    # Check if any profile is already in the command
    local profile_found=false
    for profile in $profiles; do
        for word in "${COMP_WORDS[@]}"; do
            if [[ "$word" == "$profile" ]]; then
                profile_found=true
                break 2
            fi
        done
    done

    if [[ "$profile_found" == false ]]; then
        COMPREPLY=( $(compgen -W "$profiles -h" -- "$cur") )
        return 0
    fi

    # if function '__git_main' is available call it otherwise return most common git commands
    if command -v __git_main >/dev/null 2>&1; then
        COMP_WORDS=($git_command)
        __git_main
        return 0
    else
        COMPREPLY=( $(compgen -W "add commit push pull status checkout branch cherry-pick stash fetch rm clone" -- "$cur") )
        return 0
    fi
}
