#!/usr/bin/env bash

_git_rmprofile() {
    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    local profiles
    profiles=$(find "$GIT_PROFILE_DIR" -type f -name '.*' -exec basename {} \; 2>/dev/null | sed 's/^\.//')

    COMPREPLY=( $(compgen -W "$profiles -h" -- "$cur") )
    return 0
}
