#!/usr/bin/env bash

_git_rmprofile() {
    local cur prev words cword
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cword="${#COMP_WORDS[@]}"
    words="${COMP_WORDS[@]}"

    local profiles
    profiles=$(find "$GIT_PROFILE_DIR" -type f -name '.*' -printf "%f\n" 2>/dev/null | sed 's/^\.//')

    # Complete profile (third word)
    if [[ "$cword" -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "$profiles -h" -- "$cur") )
        return 0
    fi

    COMPREPLY=("")
    return 0
}
