#!/usr/bin/env bash

_serve() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="--port --host --proxy --dirlist --help -h"

  case "$prev" in
    --dirlist)
      COMPREPLY=( $(compgen -W "true false" -- "$cur") )
      return 0
      ;;
    --port|--host|--proxy)
      return 0
      ;;
  esac

  # Filter out options that have already been used
  local used_opts=()
  for ((i=1; i < COMP_CWORD; i++)); do
    if [[ ${COMP_WORDS[i]} == --* ]]; then
      used_opts+=(${COMP_WORDS[i]})
    fi
  done

  local available_opts=()
  # If there's at least one flag already used, remove help options
  if [ ${#used_opts[@]} -gt 0 ]; then
    opts=${opts// -h}
    opts=${opts//--help/}
  fi

  for opt in $opts; do
    if [[ ! " ${used_opts[@]} " =~ " $opt " ]]; then
      available_opts+=("$opt")
    fi
  done

  COMPREPLY=( $(compgen -W "${available_opts[*]}" -- "$cur") )
}
