#!/usr/bin/env bash

_youtube_get() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="bestaudio mp3 bestvideo mp4"

    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    else
        COMPREPLY=()  # Let bash handle URLs or use default completion
    fi
    return 0
}
