#!/usr/bin/env bash

SCRIPT=$(basename "$0")

HELP_MESSAGE="Usage: $SCRIPT

Clones rc and sources it to the shell configuration file.

options:
  -h, --help    Show help message and exit."

# Help message
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echo "$HELP_MESSAGE"
  exit 0
fi

set -euo pipefail

echo "Preparing to clone rc repository..."
start_dir=$(pwd)
cd "$HOME"
mkdir -p Repositories/
cd Repositories/

if [ -d "rc" ]; then
    echo "rc repository already exists. Pulling latest changes..."
    cd rc
    git pull
    cd ..
else
    echo "Cloning rc repository..."
    git clone https://github.com/nightmaregaurav/rc.git
fi

echo "Writing source line to shell rc files..."
rc_files=("$HOME/.bashrc" "$HOME/.zshrc")
for shell_rc in "${rc_files[@]}"; do
  if [ -f "$shell_rc" ]; then
      if ! grep -q "source \"$HOME/Repositories/rc/activate\"" "$shell_rc"; then
          echo "source \"$HOME/Repositories/rc/activate\"" >> "$shell_rc"
          echo "Updated $shell_rc"
      else
          echo "$shell_rc already contains the source line."
      fi
  else
    echo "source \"$HOME/Repositories/rc/activate\"" >> "$shell_rc"
    echo "Created $shell_rc and added the source line."
  fi
done

cd "$start_dir"