#!/usr/bin/env bash

SCRIPT=$(basename "$0")

HELP_MESSAGE="Usage: $SCRIPT

Clones rc using ssh URL and sources it to the shell configuration file.

options:
  -h, --help    Show help message and exit."

# Help message
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echo "$HELP_MESSAGE"
  exit 0
fi

echo "Determining shell configuration file..."
if [ -n "$ZSH_VERSION" ]; then
    shell_rc="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
    shell_rc="$HOME/.bashrc"
else
    echo "Unsupported shell. Please add 'source \"$HOME/Repositories/rc/rc.sh\"' to your shell configuration file manually."
    cd "$start_dir"
    exit 1
fi

set -euo pipefail

echo "Cloning rc repository..."
start_dir=$(pwd)
cd "$HOME"
mkdir -p Repositories/
cd Repositories/
git clone git@github.com:nightmaregaurav/rc.git

echo "Writing source line to shell rc files..."
if [ -f "$shell_rc" ]; then
    if ! grep -q "source \"$HOME/Repositories/rc/rc.sh\"" "$shell_rc"; then
        echo "source \"$HOME/Repositories/rc/rc.sh\"" >> "$shell_rc"
        echo "Updated $shell_rc"
    else
        echo "$shell_rc already contains the source line."
    fi
else
  echo "source \"$HOME/Repositories/rc/rc.sh\"" >> "$shell_rc"
  echo "Created $shell_rc and added the source line."
fi

cd "$start_dir"
