#!/usr/bin/env bash

SCRIPT=$(basename "$0")

HELP_MESSAGE="Usage: $SCRIPT

Clones rc, setup required environment and sources it to the shell configuration file.

options:
  -h, --help    Show help message and exit."

# Help message
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echo "$HELP_MESSAGE"
  exit 0
fi

# if there is no argument, set it as --start to avoid unbound variable error
if [[ $# -eq 0 ]]; then
  set -- "--start"
fi

set -euo pipefail

# Get current user and group
start_dir=$(pwd)

if [[ "$1" == "--repo" ]]; then
  echo "Preparing to clone rc repository..."
  cd /opt/rc
  if [ -d .git ]; then
      echo "rc repository already exists. Pulling latest changes..."
      git pull
      cd ..
  else
      echo "Cloning rc repository..."
      git clone https://github.com/nightmaregaurav/rc.git .
  fi

  exec "$0" "--shell"
fi

if [[ "$1" == "--shell" ]]; then
  echo "Writing source line to shell rc files..."
  sudo tee /etc/profile.d/nightmaregaurav-rc.sh > /dev/null <<EOF
#!/bin/sh

source /opt/rc/activate
EOF
  echo "Created rc profile source script at /etc/profile.d/nightmaregaurav-rc.sh"

  set +euo pipefail
  echo "Sourcing activate script directly to activate rc in the current shell..."
  source /opt/rc/activate

  cd "$start_dir"

  exec "$0" "--uv"
fi

if [[ "$1" == "--uv" ]]; then
  set -euo pipefail
  echo "Setting up uv..."
  echo "Detecting operating system..."
  OS="$(uname -s)"
  case "$OS" in
      Darwin)
          echo "Detected macOS."
          if ! command -v brew >/dev/null 2>&1; then
              echo "Homebrew not found. Please install Homebrew first: https://brew.sh/"
              exit 1
          fi
          echo "Installing uv with Homebrew..."
          brew install uv
          ;;

      Linux)
          # if $TERMUX_VERSION env var is set it's Android(termux)
          set +u
          if [[ -n "$TERMUX_VERSION" ]]; then
              echo "Detected Android(termux)."
              echo "Installing uv with pkg..."
              pkg install uv
          else
              echo "Detected Linux."
              echo "Installing uv with curl..."
              curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          set -u
          ;;

      MINGW*|MSYS*|CYGWIN*|Windows_NT)
          echo "Detected Windows."
          if ! command -v winget >/dev/null 2>&1; then
              echo "winget not found. Please make sure you're running this in a Windows environment with winget available."
              exit 1
          fi
          echo "Installing uv with winget..."
          winget install --id=astral-sh.uv -e --source winget
          ;;

      *)
          echo "Unsupported OS: $OS"
          exit 1
          ;;
  esac
  echo "Installing Python versions 3.13 and 3.14 using uv..."
  uv python install 3.14
  uv python install 3.13
  echo "Installing argcomplete package using uv..."
  uv tool install argcomplete
  echo "Setup completed successfully."
fi

USER=$(whoami)
sudo mkdir -p /opt/rc
if ! getent group rc-script-users > /dev/null; then
    sudo groupadd rc-script-users
    echo "Group 'rc-script-users' created."
else
    echo "Group 'rc-script-users' already exists."
fi
echo "Adding root and $USER to 'rc-script-users' group..."
sudo usermod -aG rc-script-users root
sudo usermod -aG rc-script-users "$USER"
echo "Changing ownership of /opt/rc to root:rc-script-users..."
sudo chown -R root:rc-script-users /opt/rc
echo "Setting group write permissions on /opt/rc..."
sudo chmod -R g+rw /opt/rc
echo "Reload user groups for current session..."
exec newgrp rc-script-users "@0" "--repo"
