#!/usr/bin/env -S uv run --script

# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "argcomplete",
#     "pynput",
# ]
# ///

import argparse
import argcomplete
from pynput.keyboard import Listener, Key

last_pressed_key = None
specialKeys = [key.name.upper() for key in Key]

def handle_key_press(key):
    """
    Handles key event and prints the corresponding HTML-like format to the console.
    """
    global last_pressed_key
    try:
        key_name = key.name.upper() if isinstance(key, Key) else key.char.upper()
        if key_name in specialKeys:
            print(f"<{key_name}>", end="", flush=True)
        else:
            print(key_name, end="", flush=True)
        last_pressed_key = key
    except AttributeError:
        pass

def handle_key_release(key):
    """
    Handles key release event and prints the corresponding HTML-like format to the console.
    """
    global last_pressed_key
    try:
        key_name = key.name.upper() if isinstance(key, Key) else key.char.upper()
        if key_name in specialKeys and last_pressed_key == key:
            # remove last character (">") and add "/>"
            print("\b/>", end="", flush=True)
        elif key_name in specialKeys:
            print(f"</{key_name}>", end="", flush=True)
        last_pressed_key = None
    except AttributeError:
        pass

def on_press(key: Key):
    """
    Called when a key is pressed.
    """
    handle_key_press(key)


def on_release(key: Key):
    """
    Called when a key is released.
    """
    handle_key_release(key)


def start_listening():
    """
    Start listening to the keyboard for key presses.
    """
    with Listener(on_press=on_press, on_release=on_release) as listener:
        listener.join()


# ---------------------------
#  MAIN LOGIC
# ---------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Captures keypresses and prints them in a typewriter format with HTML-like tags.",
        formatter_class=argparse.RawTextHelpFormatter,
        add_help=False,
    )

    parser.add_argument("-h", "--help", action="help", help="Show help message and exit.")

    argcomplete.autocomplete(parser, always_complete_options=False)
    parser.parse_args()

    # Start listening to user input after script runs
    print("Press any keys. Press ESC to exit.")
    start_listening()


if __name__ == "__main__":
    main()
